//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADPClientWebDemo.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
          {
          ""clientID"": ""ec762f06-7410-4f6d-aa82-969902c1836a"",
          ""clientSecret"": ""6daf2cd7-4604-46c0-ab43-a645a6571d34"",
          ""sslCertPath"": ""~/Content/certs/apiclient_iat.pfx"",
          ""sslKeyPath"": ""~/Content/certs/apiclient_iat.key"",
          ""sslKeyPass"": ""adpadp10"",
          ""tokenServerURL"": ""https://iat-api.adp.com/auth/oauth/v2/token"",
          ""disconnectURL"": ""https://iat-accounts.adp.com/auth/oauth/v2/logout"",
          ""apiRequestURL"": ""https://iat-api.adp.com"",
          ""baseAuthorizationURL"": ""https://iat-accounts.adp.com/auth/oauth/v2/authorize"",
          ""redirectURL"": ""http://localhost:8889/callback"",
          ""accessScope"": ""hr.workerInformationManagement.workerManagement.workerViewing.worker.read hr.workerInformationManagement.workerManagement.associateManagment.associate.read hr.workerInformationManagement.workerManagement.employeeManagement.employee.read"",
          ""responseType"": ""code"",
          ""scope"": ""openid"",
          ""defaultexpiration"": 3600,
          ""grantType"": ""authorization_code""
          }
        ")]
        public string AuthorizationCodeConfiguration {
            get {
                return ((string)(this["AuthorizationCodeConfiguration"]));
            }
        }
    }
}
